alias: Check Timers on Startup
description: Checks all persistent timers after HA reboot
trigger:
  - platform: event
    event_type: homeassistant_started
condition: []
action:
  - service: automation.trigger
    data:
      entity_id: "{{ states.input_datetime | selectattr('entity_id', 'match', 'input_datetime.*_timer') | selectattr('state', '>', '1970-01-01 00:00:00') | map(attribute='entity_id') | map('replace', 'input_datetime.', 'automation.') | list }}"
mode: single